// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7D0CHg5VNcXwxHycrFkNrPNRBNomOrAE',
    appId: '1:935488843940:web:bb0445e79a9e2b0385b631',
    messagingSenderId: '935488843940',
    projectId: 'foodquest1-aa0c7',
    authDomain: 'foodquest1-aa0c7.firebaseapp.com',
    storageBucket: 'foodquest1-aa0c7.appspot.com',
    measurementId: 'G-QQTPHB1LL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnmWCc3HhnTuFjdpgF9OGh1-5a1G6wHWI',
    appId: '1:935488843940:android:9fcb6cbaa6dc68fa85b631',
    messagingSenderId: '935488843940',
    projectId: 'foodquest1-aa0c7',
    storageBucket: 'foodquest1-aa0c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE-h_dC39AUlgmk2zXgdRUez011CNgOUs',
    appId: '1:935488843940:ios:c2af3c6649fe8f9c85b631',
    messagingSenderId: '935488843940',
    projectId: 'foodquest1-aa0c7',
    storageBucket: 'foodquest1-aa0c7.appspot.com',
    iosClientId: '935488843940-hi8r6n76bgpvt49he2c5spkcjfpj1guq.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE-h_dC39AUlgmk2zXgdRUez011CNgOUs',
    appId: '1:935488843940:ios:c2af3c6649fe8f9c85b631',
    messagingSenderId: '935488843940',
    projectId: 'foodquest1-aa0c7',
    storageBucket: 'foodquest1-aa0c7.appspot.com',
    iosClientId: '935488843940-hi8r6n76bgpvt49he2c5spkcjfpj1guq.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7D0CHg5VNcXwxHycrFkNrPNRBNomOrAE',
    appId: '1:935488843940:web:85cb9933d4b7c5cc85b631',
    messagingSenderId: '935488843940',
    projectId: 'foodquest1-aa0c7',
    authDomain: 'foodquest1-aa0c7.firebaseapp.com',
    storageBucket: 'foodquest1-aa0c7.appspot.com',
    measurementId: 'G-Z0GR47RB04',
  );

}